### PR TITLE
Make mongodb moves possible

### PR DESCRIPTION
**Pull request by somehowchris**
This change includes a command being executed before the backup which will drop every collection and the backup command to not care about the origins database name

### CODE REVIEW

**Review by JamesClonk — CHANGES_REQUESTED** [review]
Hi @somehowchris 

Thanks for this PR, could you run it through gofmt to reformat the contents though? The lines seem to not be properly formatted. 
(Hopefully that will also retrigger the CircleCI build pipeline, I seem to have accidentally disabled it for PRs)

Looks good otherwise. 👍

**Comment by somehowchris** [comment]
@JamesClonk Ich werde leider nicht wirklich aus den logs von circleci schlauer. Da der code bei uns funktioniert und wir auch schon erfolgreich Datenbanken migriert haben verwirrt mich dies

**Comment by JamesClonk** [comment]
@somehowchris Aus irgendeinem Grund scheint der Restore Status nicht auf "success" zu stehen laut Built Pipeline, Zeile https://github.com/swisscom/backman/blob/6d6d351c83141142e7dd1b7b5999e3bae27da500/scripts/mongodb.sh#L96
Wenn du ein Restore von MongoDB bei dir lokal ausführst, gibt eine Statusabfrage auf den API Endpoint ein "success" zurück bei dir?

**Comment by somehowchris** [comment]
@JamesClonk Let's me start by saying, I know that code works 🤓 

I actually spent like 3 hours tracing what the problem could be a fixing the tests but I couldn't find the golden solution.
So here is what's not working:

I double checked the env variables.
The mongodb creds in the apps I have look like
```json
{
   "host": "xyz.host.url",
   "database":"my_mongodb",
   "password": "pass",
   "username":"username",
   "uri":"mongodb://username:pass@xyz.host.url/my_mongodb"
}
```
>They usually have replica sets but thats an added bonus.

The test failes because the previous code backs up the whole cluster, my restore code only backups up to 1 database as I thought we are talking about managed services where we usually only have 1. Also the env variables of uri and database were not set as expected and used by the test script. It fails because the admin user doesn't need specific access for a single db but rather can login and access the db.

I tried using the bitnami mongodb image but couln't find the restore problem.

**Comment by JamesClonk** [comment]
@somehowchris It seems adding `--nsFrom` and `--nsTo` causes `mongorestore` to hang up and never finish/exit, hence the backup also never finishes successfully from backmans point of view. 
I just tried it locally on my machine, if I run `cat my_db_20201007122546.gz | mongorestore --uri mongodb://mongoadmin:super-secret@127.0.0.1:27017 --nsFrom '$prefix$.$suffix$' --nsTo 'my-db.$suffix$' --numInsertionWorkersPerCollection 16 --gzip --archive` it hangs up and never exits.
I cannot merge the PR if the mongorestore command doesn't work properly.

Also: Wouldn't just adding the `--drop` flag on mongorestore do the same thing as the additional dropCommand? Or is it something different?

**Comment by somehowchris** [comment]
`--drop` only drops the collections which are mentioned inside the backup to restore. Yes it does not work because `mongodb://mongoadmin:super-secret@127.0.0.1:27017` is not a database but a cluster

**Pull request closed without merging**
